import com.cashzhang.nozdormu.model.Token.toString
import com.cashzhang.nozdormu.MainActivity
import com.cashzhang.nozdormu.fragment.StreamsFragment
import com.cashzhang.nozdormu.fragment.FeedsFragment
import androidx.swiperefreshlayout.widget.SwipeRefreshLayout
import com.cashzhang.nozdormu.R
import kotlin.jvm.Throws
import org.xmlpull.v1.XmlPullParserException
import org.xmlpull.v1.XmlPullParser
import org.xmlpull.v1.XmlPullParserFactory
import com.cashzhang.nozdormu.CustomListener
import io.reactivex.disposables.Disposable
import com.cashzhang.nozdormu.CustomObserver
import retrofit2.http.POST
import com.cashzhang.nozdormu.model.LoginBody
import retrofit2.http.GET
import kotlin.jvm.Volatile
import com.cashzhang.nozdormu.FeedlyApi
import com.cashzhang.nozdormu.FeedlyRequest
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import retrofit2.adapter.rxjava2.RxJava2CallAdapterFactory
import android.app.Activity
import butterknife.BindView
import android.webkit.WebView
import android.os.Bundle
import android.view.WindowManager
import butterknife.ButterKnife
import android.content.Intent
import android.webkit.WebViewClient
import io.reactivex.schedulers.Schedulers
import com.cashzhang.nozdormu.LoginActivity
import androidx.appcompat.app.AppCompatActivity
import com.cashzhang.nozdormu.MainActivity.FragmentSwitch
import com.cashzhang.nozdormu.adapter.FragmentAdapter
import com.cashzhang.nozdormu.fragment.LeftFragment
import com.cashzhang.nozdormu.fragment.CollectionsFragment
import com.cashzhang.nozdormu.fragment.ContentFragment
import androidx.viewpager.widget.ViewPager
import com.cashzhang.nozdormu.service.UpdateService
import com.cashzhang.nozdormu.ObjectIO
import io.reactivex.android.schedulers.AndroidSchedulers
import android.app.Application
import android.content.SharedPreferences